### ISSUE TITLE
Upgrade to latest esbuild to support TypeScript 4.9

### ISSUE THREAD

**Issue by tonyxiao** [esbuild-kit/esm-loader#54] opened 2023-01-31 07:08 UTC
Currently esbuild version included is 0.15.x, which fails if you try to use a ts 4.9 feature. Current workaround is to manually override the dependency of `esbuild`

<img width="1283" alt="CleanShot 2023-01-31 at 15 06 23@2x" src="https://user-images.githubusercontent.com/696842/215690209-57b6f20d-5973-458c-b263-a016f0e919a3.png">

**Comment by privatenumber** [comment] 2023-01-31 07:21
Closing as a duplicate of https://github.com/esbuild-kit/tsx/issues/171

**Closed by privatenumber** 2023-01-31 07:21 UTC
