### ISSUE TITLE
Option to disable minification

### ISSUE THREAD

**Issue by connorjclark** [esbuild-kit/esm-loader#18] opened 2022-05-26 00:15 UTC
I'm using this loader in order to run `.tsx` files in Mocha, but I noticed when attaching a debugger that the scripts were minified. It'd be nice to be able to configure the esbuild minification option to improve debugging.

**Comment by privatenumber** [comment] 2022-05-28 12:59
Should be fixed in the latest core-utils release.

You can update the subdependency or reinstall tsx

**Comment by privatenumber** [comment] 2022-05-29 20:43
Closing as fixed & duplicate of https://github.com/esbuild-kit/core-utils/issues/7

**Closed by privatenumber** 2022-05-29 20:43 UTC
Labels: duplicate
